### ISSUE TITLE
NPE when inserting entity which contain null SingleAssociation

### ISSUE THREAD

**Issue by deviant-studio** [gfx/Android-Orma#162]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'long com.github.gfx.android.orma.SingleAssociation.getId()' on a null object reference
02-13 18:04:04.063 11188-11188/ds.dbtests W/System.err:     at ds.dbtests.db.orma.OrderOrma_Schema.convertToArgs(OrderOrma_Schema.java:208)
02-13 18:04:04.063 11188-11188/ds.dbtests W/System.err:     at ds.dbtests.db.orma.OrderOrma_Schema.convertToArgs(OrderOrma_Schema.java:26)
02-13 18:04:04.063 11188-11188/ds.dbtests W/System.err:     at com.github.gfx.android.orma.Inserter.execute(Inserter.java:66)
02-13 18:04:04.063 11188-11188/ds.dbtests W/System.err:     at ds.dbtests.MainActivity.ormaWriteTest(MainActivity.kt:433)
02-13 18:04:04.063 11188-11188/ds.dbtests W/System.err:     at ds.dbtests.MainActivity.access$ormaWriteTest(MainActivity.kt:34)
02-13 18:04:04.063 11188-11188/ds.dbtests W/System.err:     at ds.dbtests.MainActivity$runTests$1$2.invoke(MainActivity.kt:113)
02-13 18:04:04.063 11188-11188/ds.dbtests W/System.err:     at ds.dbtests.MainActivity$runTests$1$2.invoke(MainActivity.kt:34)
02-13 18:04:04.063 11188-11188/ds.dbtests W/System.err:     at ds.dbtests.MainActivity.profile(MainActivity.kt:179)
02-13 18:04:04.063 11188-11188/ds.dbtests W/System.err:     at ds.dbtests.MainActivity.access$profile(MainActivity.kt:34)
02-13 18:04:04.063 11188-11188/ds.dbtests W/System.err:     at ds.dbtests.MainActivity$runTests$1.invoke(MainActivity.kt:113)
02-13 18:04:04.063 11188-11188/ds.dbtests W/System.err:     at ds.dbtests.MainActivity$runTests$1.invoke(MainActivity.kt:34)
```

**Comment by gfx** [comment]
Can you try v1.3.0?

**Comment by deviant-studio** [comment]
Actually i'm using 1.3.0 :)
If you need more info, i can provide some example

**Comment by gfx** [comment]
Please. I'd like to see the model class.

2016年2月14日(日) 18:42 deviant-studio <notifications@github.com>:

**Comment by deviant-studio** [comment]
I have 2 entities:
User and Order
user can have many orders, so i created relation in the order like:
```
class Order {
...
 @Column(indexed = true) public SingleAssociation<User> user;
}
```

When i trying to create some order and insert it immediatelly without assign specific user, it crashes:
```
Order order = new Order();
// order.user = SingleAssociation.just(userId, user); // skip assigning
orma.insertIntoOrder(order);
```
Crash occurs in autogenerated class when trying to access method on a null object reference:
http://i.imgur.com/mcw6PrH.png

More details can be found here:
https://github.com/deviant-studio/DB-Tests/blob/master/app/src/main/java/ds/dbtests/db/orma/OrderOrma.java
sorry for the mess with java/kotlin

**Comment by gfx** [comment]
Thanks to the details.

This is a specification. Use `@Nullable` if a field can be null.

**Comment by deviant-studio** [comment]
It works indeed! Thanks.
It would be nice to add some clarifications to the docs, or to the samle app.
Btw. your lib performance is pretty high, one of the fastest sqlite orm at this point :)
Great job!
http://i.imgur.com/3phZj8X.png

**Comment by gfx** [comment]
:+1:
