### ISSUE TITLE
Is OrmaRecyclerViewAdapter not supported relations which have where clauses?

### ISSUE THREAD

**Issue by gen0083** [gfx/Android-Orma#227]
I have a question to use OrmaRecyclerViewAdapter.

In example, at RecyclerViewActivity's code modify to below.
```
adapter = new Adapter(this, orma.relationOfTodo()
    .doneEq(true)  // <-- add this
    .orderByCreatedTimeAsc());
```

After this, push FAB, crash app.
```
03-16 15:59:48.300 21160-21160/com.github.gfx.android.orma.example E/AndroidRuntime: FATAL EXCEPTION: main
  Process: com.github.gfx.android.orma.example, PID: 21160
  com.github.gfx.android.orma.exception.NoValueException: Expected single value for 0 but nothing for Todo
  at com.github.gfx.android.orma.Selector.get(Selector.java:196)
  at com.github.gfx.android.orma.Relation.get(Relation.java:86)
  at com.github.gfx.android.orma.widget.OrmaAdapter.getItem(OrmaAdapter.java:79)
  at com.github.gfx.android.orma.widget.OrmaRecyclerViewAdapter.getItem(OrmaRecyclerViewAdapter.java:77)
  at com.github.gfx.android.orma.example.activity.RecyclerViewActivity$Adapter.onBindViewHolder(RecyclerViewActivity.java:116)
  at com.github.gfx.android.orma.example.activity.RecyclerViewActivity$Adapter.onBindViewHolder(RecyclerViewActivity.java:102)
  at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5453)
  at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:5486)
  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4723)
  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4599)
  at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1988)
  at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1384)
  at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1347)
  at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:574)
  at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3003)
  at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2881)
  at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3265)
  at android.view.View.layout(View.java:15671)
  at android.view.ViewGroup.layout(ViewGroup.java:5038)
  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
  at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
  at android.view.View.layout(View.java:15671)
  at android.view.ViewGroup.layout(ViewGroup.java:5038)
  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
  at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
  at android.view.View.layout(View.java:15671)
  at android.view.ViewGroup.layout(ViewGroup.java:5038)
  at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:435)
  at android.view.View.layout(View.java:15671)
  at android.view.ViewGroup.layout(ViewGroup.java:5038)
  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
  at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
  at android.view.View.layout(View.java:15671)
  at android.view.ViewGroup.layout(ViewGroup.java:5038)
  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
  at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
  at android.view.View.layout(View.java:15671)
  at android.view.ViewGroup.layout(ViewGroup.java:5038)
  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
  at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
  at android.view.View.layout(View.java:15671)
  at android.view.ViewGroup.layout(ViewGroup.java:5038)
  at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2086)
  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1843)
  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
  at android.view.Choreographer.doCallbacks(Choreographer.java:580)
  at android.view.Choreographer.doFrame(Choreographer.java:550)
  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
  at android.os.Handler.handleCallback(Handler.java:739)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:135)
  at android.app.ActivityThread.main(ActivityThread.java:5254) 
```

1. New Todo inserted to database by addItemAsObservable
1. TotalCount of adapter increased
1. Fire notifyItemInserted(getItemCount())
1. RecyclerView going to get new Todo
1. But there are no value so app crashed

Actually relation size not increased because relation have where clauses.
Added Todo's done field is false.
Relation have only done = true records.

**Comment by gfx** [comment]
Released v2.3.5. Thanks for details & a pull-request (#228).
