### ISSUE TITLE
SQLiteDatabaseLockedException: error code 5: database is locked

### ISSUE THREAD

**Issue by konifar** [gfx/Android-Orma#244]
This error occured.

```java
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.taptrip/com.taptrip.activity.HomeActivity}: android.database.sqlite.SQLiteDatabaseLockedException: error code 5: database is locked
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2096)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2123)
       at android.app.ActivityThread.access$600(ActivityThread.java:135)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1248)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:4643)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:809)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:576)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by android.database.sqlite.SQLiteDatabaseLockedException: error code 5: database is locked
       at android.database.sqlite.SQLiteStatement.native_1x1_string(SQLiteStatement.java)
       at android.database.sqlite.SQLiteStatement.simpleQueryForString(SQLiteStatement.java:164)
       at android.database.DatabaseUtils.stringForQuery(DatabaseUtils.java:843)
       at android.database.DatabaseUtils.stringForQuery(DatabaseUtils.java:831)
       at android.database.sqlite.SQLiteDatabase.setJournalMode(SQLiteDatabase.java:1060)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:996)
       at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1051)
       at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:794)
       at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:221)
       at com.github.gfx.android.orma.OrmaConnection.openDatabase(SourceFile:100)
       at com.github.gfx.android.orma.OrmaConnection.(SourceFile)
       at com.taptrip.data.OrmaDatabase$Builder.build(SourceFile:205)
```

Maybe It seems my mistake to use Orma. But can you help or have some advise? 🙇

**Comment by gfx** [comment]
I guess you try to open a database file in multi-threads? The OrmaDatabase is designed as a singleton.

**Comment by konifar** [comment]
Right. In our app, there is preload logic on another thread. So I fix this.
I wish this fixed. Anyway, thanks for reply 😃
