### ISSUE TITLE
Releasing statement in a finalizer. Please ensure that you explicitly call close() on your cursor

### ISSUE THREAD

**Issue by zoff99** [gfx/Android-Orma#409]
i am getting lots of these with 5.0.0-rc1 with encrypted database

```
###/com.zoffcc.applications.trifa W/SQLiteCompiledSql: Releasing statement in a finalizer. Please ensure that you explicitly call close() on your cursor: INSERT INTO `table`....
net.sqlcipher.database.DatabaseObjectNotClosedException: Application did not close the cursor or database object that was opened here
at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:62)
 at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:109)
 at net.sqlcipher.database.SQLiteStatement.<init>(SQLiteStatement.java:39)
at net.sqlcipher.database.SQLiteDatabase.compileStatement(SQLiteDatabase.java:1589)
at com.github.gfx.android.orma.encryption.EncryptedDatabase.compileStatement(EncryptedDatabase.java:59)
at com.github.gfx.android.orma.Inserter.<init>(Inserter.java:56)
at com.zoffcc.applications.trifa.OrmaDatabase.prepareInsertIntoMessage(OrmaDatabase.java:307)
at com.zoffcc.applications.trifa.OrmaDatabase.prepareInsertIntoMessage(OrmaDatabase.java:290)
at com.zoffcc.applications.trifa.OrmaDatabase.insertIntoMessage(OrmaDatabase.java:282)
```

**Comment by gfx** [comment]
Thanks for the report. Fixed in #413, which is included in v5.0.0-rc3.
